# Generated by Django 6.0.2 on 2026-02-27 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='название', max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хэш пароля')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('user_class', models.CharField(db_column='класс', max_length=10, verbose_name='Класс')),
                ('role', models.CharField(default='user', max_length=20, verbose_name='Роль')),
                ('study', models.IntegerField(db_column='учеба', default=0, verbose_name='Учеба')),
                ('fun', models.IntegerField(db_column='развлечения', default=0, verbose_name='Развлечения')),
                ('health', models.IntegerField(db_column='здоровье', default=0, verbose_name='Здоровье')),
                ('points', models.IntegerField(db_column='количество_очков', default=0, verbose_name='Количество очков')),
                ('registration_date', models.DateTimeField(db_column='дата_регистрации', default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(db_column='дата_события', default=django.utils.timezone.now, verbose_name='Дата события')),
                ('action_name', models.CharField(db_column='наименование_действия', max_length=255, verbose_name='Наименование действия')),
                ('user', models.ForeignKey(db_column='Пользователь_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
                'db_table': 'Логи_действий',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_column='текст', verbose_name='Текст вопроса')),
                ('creation_date', models.DateTimeField(db_column='дата_создания', default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('category', models.ForeignKey(db_column='id_категории', on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_column='текст_ответа', verbose_name='Текст ответа')),
                ('study_change', models.IntegerField(db_column='изм_учеба', verbose_name='Изменение учебы')),
                ('fun_change', models.IntegerField(db_column='изм_развлечения', verbose_name='Изменение развлечений')),
                ('health_change', models.IntegerField(db_column='изм_здоровья', verbose_name='Изменение здоровья')),
                ('question', models.ForeignKey(db_column='id_вопроса', on_delete=django.db.models.deletion.CASCADE, to='main.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'db_table': 'Вариант_ответа',
            },
        ),
    ]
